lengow_orders/lengow_orders/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('orders.urls')),
    path('admin/', admin.site.urls),
]

lengow_orders/orders/urls.py
from . import views
from django.urls import path, include
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'order', views.OrderViewSet)

app_name = 'orders'
urlpatterns = [
    path('rest/', include(router.urls)),
    path('', views.orders, name='orders'),
    path('<str:order_id>', views.order, name='order'),
]

lengow_orders/orders/models.py
from django.db import models


# Les commentaires représentent un exemple des lignes choisies
# pour une entitée Order
class Order(models.Model):
    # <order_id>111-2222222-3333333</order_id>
    # Je suis parti du principe que ce champs est l'identifiant d'une commande
    id = models.CharField(primary_key=True, max_length=50)

    # <marketplace>amazon</marketplace>
    marketplace = models.CharField(max_length=75)

    # <idFlux>88827</idFlux>
    idFlux = models.IntegerField()

    # <order_purchase_date>2014-10-21</order_purchase_date>
    order_purchase_date = models.DateField(null=True)

    # <order_purchase_heure>14:59:51</order_purchase_heure>
    order_purchase_heure = models.TimeField(null=True)

    # <order_amount>34.5</order_amount>
    # Au vu des exemples, un chiffre après la virgule suffit.
    # J'ai peut-être vu gros avec 5 chiffres ...
    order_amount = models.DecimalField(decimal_places=1, max_digits=5)

    class Meta:
        verbose_name = "Commande"
        ordering = ['order_purchase_date']

    def __str__(self):
        return "Commande d'id {}, effectuée sur {} au sein du flux {} le {} à {} en quantité {}.".format(
            self.id, self.marketplace, self.idFlux, self.order_purchase_date,
            self.order_purchase_heure, self.order_amount)

lengow_orders/orders/views.py
from django.shortcuts import render, get_object_or_404
from .models import Order
from rest_framework import viewsets
from .serializers import OrderSerializer

# 'filter_name': 'field_name'
FIELD_SPECIFICATION = {
    'marketplace__icontains': 'marketplace',
    'idFlux': 'idflux',
    'order_purchase_date__day': 'day',
    'order_purchase_date__month': 'month',
    'order_purchase_date__year': 'year',
}


def orders(request):
    context = dict()
    orders_list = Order.objects.all()

    if request.method == "POST":
        for filter_name, field_name in FIELD_SPECIFICATION.items():
            field_value = request.POST.get(field_name)
            if field_value != '':
                print({filter_name: field_value})
                orders_list = orders_list.filter(**{filter_name: field_value})
                context[field_name] = field_value

    context['orders_list'] = orders_list
    return render(request, 'orders/orders.html', context)


def order(request, order_id):
    my_order = get_object_or_404(Order, id=order_id)
    context = {'order': my_order}
    return render(request, 'orders/order.html', context)


class OrderViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows orders to be viewed or edited.
    """
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

lengow_orders/orders/templates/orders/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order</title>

    {% load static %}
    <link rel="stylesheet" href='{% static "orders/css/bootstrap4_4_1.min.css" %}'>
</head>
<body style="padding-top:56px;">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Orders</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsOrders" aria-controls="navbarsOrders" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsOrders">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'orders:orders' %}">All orders<span class="sr-only"></span></a>
                </li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6>Order id : {{order.id}}</h6>

            {% if order %}
                <ul>
                    <li>Marketplace : {{order.marketplace}}</li>
                    <li>Id Flux : {{order.idFlux}}</li>
                    <li>Date : {{order.order_purchase_date}}</li>
                    <li>Hour : {{order.order_purchase_heure}}</li>
                    <li>Amount : {{order.order_amount }}</li>
                </ul>
            {% else %}
                <p>No order are available.</p>
            {% endif %}

        </div>
        <small class="d-block text-left mt-3">
          <a href="{% url 'orders:orders' %}">Retour</a>
        </small>
    </main>

    <script src='{% static "orders/js/jquery_3_4_1.slim.min.js" %}'></script>
    <script src='{% static "orders/js/popper.min.js" %}'></script>
    <script src='{% static "orders/js/bootstrap.min.js" %}'></script>
</body>
</html>

lengow_orders/orders/templates/orders/orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Orders</title>

    {% load static %}
    <link rel="stylesheet" href='{% static "orders/css/bootstrap4_4_1.min.css" %}'>
</head>
<body style="padding-top:56px;">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Orders</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsOrders" aria-controls="navbarsOrders" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsOrders">
            <ul class="navbar-nav mr-auto">
<!--                <li class="nav-item active">-->
<!--                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
<!--                </li>-->
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'orders:orders' %}" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2" aria-label="Marketplace" name="marketplace" type="text"
                               placeholder="Marketplace..." {% if marketplace %} value="{{marketplace}}" {% endif %}>
                <input class="form-control mr-sm-2" aria-label="IdFlux" name="idflux" type="text" placeholder="IdFlux..."
                           {% if idflux %} value="{{idflux}}" {% endif %}>
                <input class="form-control mr-sm-2" aria-label="Day" name="day" type="text" placeholder="Day (DD)..."
                           {% if day %} value="{{day}}" {% endif %}>
                <input class="form-control mr-sm-2"  aria-label="Month" name="month" type="text" placeholder="Month (MM)..."
                           {% if month %} value="{{month}}" {% endif %}>
                <input class="form-control mr-sm-2"  aria-label="Year" name="year" type="text" placeholder="Year (YYYY)..."
                           {% if year %} value="{{year}}" {% endif %}>
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search an order !</button>
            </form>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            {% if orders_list %}
                {% for order in orders_list %}
                    <div class="media text-muted pt-3">
                        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <a href="{% url 'orders:order' order.id %}"><strong class="d-block text-gray-dark">Order {{order.id}}</strong></a>
                        Marketplace : {{order.marketplace}}
                        </p>
                    </div>
                {% endfor %}
            {% else %}
                <div class="media text-muted pt-3">
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <strong class="d-block text-gray-dark">No order found !</strong>
                    </p>
                </div>
            {% endif %}
        </div>
    </main>

    <script src='{% static "orders/js/jquery_3_4_1.slim.min.js" %}'></script>
    <script src='{% static "orders/js/popper.min.js" %}'></script>
    <script src='{% static "orders/js/bootstrap.min.js" %}'></script>
</body>
</html>